### ISSUE TITLE
Update the acme certificate jobs for better error handling and output more info logs

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/cg-provision#1574]
Update the acme [provision](https://github.com/cloud-gov/cg-provision/blob/main/ci/provision-certificate.sh) and [upload](https://github.com/cloud-gov/cg-provision/blob/main/ci/upload-certificate.sh) steps to:

- Contain more non-sensitive information about that actions are being executed so operators know what is taking place
- Improve error handling on certbot and AWS IAM errors so operators know current state of the operation and/or where it failed

## Acceptance Criteria

- [ ] Pipeline job output explains the steps on when a provision takes place, when a provision is skipped due to cert is not old enough
- [ ] Pipeline job output explains what the upload step is doing, what it found, and what it is trying to do
- [ ] For certbot provision, improve error handing and messaging around a provision failure without leaking IP
- [ ] For upload, improve the AWS error handling and messaging around the upload and any deletion steps without leaking IP

**Comment by wz-gsa** [comment]
confirmed with @soutenniza this can be closed
