### ISSUE TITLE
Fix terraform 

### ISSUE THREAD

**Issue by tammersaleh** [cloud-gov/cg-provision#735]
Fixing ourselves out of [this mess](https://docs.google.com/document/d/19LDEX8ac46JkPgoJUoSAJCf2B0K5D_QpX6O1IdO8w7Q/edit)

- [x] Delete domain broker v2 app in cf dev/staging/prod
- [x] Pause pipeline jobs
- [ ] Branch master/HEAD^1 into fixing
- [ ] Point pipeline at fixing
- [ ] Get dev and staging to plan and apply clean against fixing
- [ ] Plan prod against fixing and should be clean
- [ ] Point pipeline at master
- [ ] search terraform state for more duplicate `type`/`name` tuples
- [ ] State surgery on Dev
- [ ] Plan & apply dev should be clean.
- [ ] State surgery on staging
- [ ] Plan & apply staging should be clean.
- [ ] State surgery on external-staging
- [ ] Plan & apply external-staging should be clean.
- [ ] State surgery on prod
- [ ] Plan & apply prod should be clean.
- [ ] State surgery on external-prod
- [ ] Plan & apply external-prod should be clean.

**Comment by tammersaleh** [comment]
Talked with @bengerman13 and @spgreenberg, and we agreed to punt on this.  Instead, we reverted the v2 removal entirely, and ensured all TF envs planned and applied clean.

**Comment by bengerman13** [comment]
@tammersaleh I think this should still be open, but waiting to be prioritized, right? we still probably want to do this in the not-horribly-distant future?

**Comment by tammersaleh** [comment]
Fair.  /cc @ccostino & @ChrisMcGowan for prioritization

**Comment by tammersaleh** [comment]
re-re-discussed and decided to close and leave a link to this issue in the comments.

**Comment by bengerman13** [comment]
We did it!!!!!!!
