### ISSUE TITLE
WAF for application ALBs

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-provision#821]
In order to add DoS and basic application protection, we want WAF on our application ALBs. Note that this should include the app and custom domain ALBs

We should consider including rate limits by default.

--- 

## Security considerations
This should improve security by blocking unwanted traffic and improve robustness during DoS-type incidents

**Comment by pburkholder** [comment]
For the record, this work to provide additional WAF protection for our ALBs was approved by FedRAMP and we were able to implement in January 2022.
