### ISSUE TITLE
Implement WAF Custom Rules process

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/cg-provision#912]
In order to add custom rules per FedRAMP proces, we want the [process we've drafted](https://docs.google.com/document/d/1j47ZlaSegSaj89OKazaXiRHRux1eE_LeOlPsIleyb6I/edit#) to be made real and described in the README

Update 2022-01-04 for closing criteria:
- [ ] Pass off to Peter to ensure SSP is up-to-date
- [ ] Implement the rules necessary to close CG285-AU-5 and CG286-SC-5 and CG146 

--- 

## Security considerations
a) this issue is safe to discuss because we only reference use of WAF, not details. b) the work has been reviewed per the document history, and will be fully reviewed by 3pao before production use.

**Comment by mogul** [comment]
@soutenniza can you give us an update on this work and move it out of `Blocked` if we're ready to move forward?

**Comment by pburkholder** [comment]
We also need to ensure we've taken care of the UAA URLs we want to block.

**Comment by pburkholder** [comment]
Van - this is all done, right? Including the blocking of system-specific URLs?

**Comment by pburkholder** [comment]
@soutenniza Is this all done?

**Comment by pburkholder** [comment]
@soutenniza Is this all done (sorry to repeat myself)?

**Comment by Chiakao** [comment]
@soutenniza Any updates on this?

**Comment by pburkholder** [comment]
I'm going to close this since any WAF custom rules will be tied into the Shield for CloudFront effort, and this was tied back to CovidTest '22
